name: Type check
description: "Runs Quilt’s type-check command on your workspace"
inputs:
  arguments:
    description: "Additional arguments to pass to sewing-kit’s type-check command"
    required: false
    default: ""
  command:
    description: "The command to run to start sewing-kit’s type-check"
    required: false
    default: "node_modules/.bin/sewing-kit type-check"
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v2
      id: typescript-cache
      name: Restore TypeScript cache
      with:
        path: |
          **/build/typescript/
          **/*.tsbuildinfo
        key: ${{ runner.os }}-typescript-v1-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-typescript-v1-

    - name: Type check
      run: ${{ inputs.command }} ${{ inputs.arguments }}
      shell: bash
